export type ArticleKind = "CHARACTER" 
  | "CREATURE" 
  | "DIARYENTRY" 
  | "ENCOUNTER" 
  | "ITEM" 
  | "LOCATION" 
  | "MAP" 
  | "MARKER_TYPE" 
  | "MARKER_TYPE_TYPE"
  | "ORGANIZATION"
  | "QUEST"
  | "QUOTE"
  | "RULE"
  | "SPELL"
  | "USER"
  | "SESSION"
  | "SESSIONAUDIO"
  
  export type OverviewItem = any;