export const ALL_REGULAR_ICONS = [
  'comments',
  'magic',
  'times',
  'map',
  'file-audio-o',
  'book',
  'user',
  'user-plus',
  'user-circle',
  'group',
  'envelope-o',
  'database',
  'trash',
  'plus',
  'table',
  'check',
  'refresh',
  'pencil',
  'arrow-left',
  'arrow-right',
  'hourglass',
  'spinner',
  'search',
  'volume-up',
  'clock-o',
  'info-circle',
  'calendar',
  'lock',
  'plus-square',
  'home',
  'th-list',
  'chevron-down',
  'chevron-up',
  'chevron-left',
  'chevron-right',
  'hammer',
  'upload',
] as const;

type typedRegularIcons = typeof ALL_REGULAR_ICONS;
export type RegularIcon = typedRegularIcons[number]; // this compiles to 'comments' | 'magic'...

export const ALL_SOLID_ICONS = [
  'male',
  'book-open',
  'compass',
  'sitemap',
  'question-circle',
  'file-import',
  'hand-sparkles',
  'calendar-alt',
  'monument',
  'store',
  'crown',
  'dungeon',
  'water',
  'chess-rook',
  'hat-wizard',
  'gavel',
  'bars',
  'tree',
  'diamond',
  'mountain',
  'tint',
  'umbrella-beach',
  'place-of-worship',
  'anchor',
  'paw',
  'fa-fort-awesome',
  'exclamation',
  'moon',
  'university',
  'hotel',
  'dice',
  'globe-americas',
  'location-dot',
  'dragon',
  'sign-out-alt',
  'user-cog',
  'pen',
  'desktop',
  'hourglass-half',
  'download',
  'redo-alt',
  'cog',
  'cut',
  'info',
  'file',
  'xmark',
  'circle-exclamation',
  'arrow-left-long',
  'arrow-right-long',
  'arrow-up-long',
  'arrow-down-long',
  'copy',
  'clipboard',
  'up-long',
  'down-long',
  'tag',
  'square-check',
  'triangle-exclamation',
  'right-from-bracket',
  'users-gear',
] as const;

type typedSolidIcons = typeof ALL_SOLID_ICONS;
export type SolidIcon = typedSolidIcons[number]; // this compiles to 'male' | 'book-open'...

export type Icon = SolidIcon | RegularIcon;
